#!/bin/bash

#Установка апач и нгинкс в качестве бэкэнда и фронтенда соответственно
mkdir /etc/httpd/sites-enabled/
chmod 777 /etc/httpd/sites-enabled/
cp ./nginx.conf /etc/nginx/nginx.conf
cp ./httpd.conf /etc/httpd/conf/
cp ./example.conf /etc/httpd/sites-enabled/
systemctl restart nginx
systemctl restart httpd
#Установка докера с MySQL в качестве мастер сервера репликаций
docker run -d --name=master_mysql --hostname=master -v $PWD/d0:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 mysql/mysql-server:8.0 --server-id=1 --log-bin=
docker exec -it master_mysql mysql -uroot -pmypass -e "CREATE USER 'repl'@'%' IDENTIFIED WITH mysql_native_password BY 'slavepass';" -e "GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';" -e "SHOW MASTER STATUS;"
#Установка мониторинга через докер
docker run -d -p 9100:9100 --name=node_exporter prom/node-exporter
docker run -d -p 9090:9090 --name=prometheus -v ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
docker run -d -p 3000:3000 --name=grafana grafana/grafana
#Установка Elastic
rpm --install elasticsearch-8.9.2-x86_64.rpm
systemctl daemon-reload
systemctl start elasticsearch
systemctl enable --now elasticsearch.service
cp ./elasticsearch.yml /etc/elasticsearch/
systemctl daemon-reload
systemctl enable --now elasticsearch.service
systemctl restart elasticsearch
curl http://localhost:9200
#Установка Kibana
rpm --install kibana-8.9.2-x86_64.rpm
systemctl daemon-reload
systemctl enable --now kibana.service
cp ./kibana.yml /etc/kibana/kibana.yml
systemctl restart kibana
#Установка Logstash
rpm --install logstash-8.9.2-x86_64.rpm
systemctl enable --now logstash.service
cp ./logstash.yml /etc/logstash/logstash.yml
cp ./logstash-nginx-es.conf /etc/logstash/conf.d/logstash-nginx-es.conf
systemctl restart logstash.service
#Установка Filebeat
rpm --install filebeat-8.9.2-x86_64.rpm
cp ./filebeat.yml /etc/filebeat/filebeat.yml
systemctl restart filebeat
history
